version: '3.8'

services:
  frontend:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8080:8080"
